// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtJ84E-n6H_SHn5w0G5eW_Xvpe7Di3HIU',
    appId: '1:570844827713:web:a5586e09b4609c5aefb6c0',
    messagingSenderId: '570844827713',
    projectId: 'fir-memo-app-c4870',
    authDomain: 'fir-memo-app-c4870.firebaseapp.com',
    storageBucket: 'fir-memo-app-c4870.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBT5N_gY2sFOdHd3jnoJRBfR7FfYHUoA8',
    appId: '1:570844827713:android:0a1db61fea1e2a08efb6c0',
    messagingSenderId: '570844827713',
    projectId: 'fir-memo-app-c4870',
    storageBucket: 'fir-memo-app-c4870.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZWZVZ0LrQijeTfbf8UcGJCNfUXC-ZFlM',
    appId: '1:570844827713:ios:5b97b4ba5652597fefb6c0',
    messagingSenderId: '570844827713',
    projectId: 'fir-memo-app-c4870',
    storageBucket: 'fir-memo-app-c4870.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZWZVZ0LrQijeTfbf8UcGJCNfUXC-ZFlM',
    appId: '1:570844827713:ios:8bfbaf58adb17d4fefb6c0',
    messagingSenderId: '570844827713',
    projectId: 'fir-memo-app-c4870',
    storageBucket: 'fir-memo-app-c4870.appspot.com',
    iosBundleId: 'com.example.firebasePractice.RunnerTests',
  );
}
